import Head from 'next/head'
import React from 'react';
import Navbar from '../components/Navbar';
import ResourceHighlight from '../components/ResourceHighlight';
import NewsLetters from '../components/Newsletters';
import ResourseList from '../components/ResourceList';
import Footer from '../components/Footer';
import styles from '../styles/Home.module.css'


const Home =()=> {
  return (
    <>
      <Head>
        <title>Content Manager</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar/>
      <ResourceHighlight/>
      <NewsLetters/>
      <ResourseList/>
      <Footer/>
      
  {/* <script>
    {
    document.addEventListener('DOMContentLoaded', () => {

      // Get all "navbar-burger" elements
      const $navbarBurgers = Array.prototype.slice.call(document.querySelectorAll('.navbar-burger'), 0);

      // Check if there are any navbar burgers
      if ($navbarBurgers.length > 0) {

        // Add a click event on each of them
        $navbarBurgers.forEach(el => {
          el.addEventListener('click', () => {

            // Get the target from the "data-target" attribute
            const target = el.dataset.target;
            const $target = document.getElementById(target);

            // Toggle the "is-active" class on both the "navbar-burger" and the "navbar-menu"
            el.classList.toggle('is-active');
            $target.classList.toggle('is-active');

          });
        });
      }
    })
    }
  </script> */}

    </>
  )
}
export default Home;
